name: Deploy FetchDataFuctions to Azure Function

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'FetchDataFunctions/**'

env:
  AZURE_FUNCTIONAPP_NAME: alpinehutsdatafetcher   # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './FetchDataFunctions'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.x'              # set this to the dotnet version to use

jobs:
  function_build_and_deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Function Build using Dotnet'
      run: |
        cd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output

    - name: 'Deploy Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_DATAFETCHER_PUBLISH_PROFILE }}